### ISSUE TITLE
process out of memory

### ISSUE THREAD

**Issue by stevenmusumeche** [fmarcia/UglifyCSS#25]
I am trying to run a very large (30k lines) CSS file through uglifycss using the following command:

    '/usr/local/bin/node' '/usr/bin/uglifycss' '/tmp/inputhmo4tj'

I get the following error:

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
    Aborted (core dumped)

How can I allocate more memory to this process or solve it in some other way?

**Comment by fmarcia** [comment]
Hi, thanks for the feedback.
Did you try to use the flag `max_old_space_size` (http://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory)?

**Comment by stevenmusumeche** [comment]
Yes, I did and got the same error:

`'/usr/local/bin/node' '/usr/bin/uglifycss' /tmp/inputdsbYCy --max_old_space_size=2000000`

**Comment by fmarcia** [comment]
Could you check with last commits? If it doesn't work, could you post your css file?

**Comment by fmarcia** [comment]
I make a few tests with even bigger files (65 K-lines, 1.6 MB) and it works flawlessly with last updates.

Besides, your command should be:
`'/usr/local/bin/node' --max_old_space_size=2000000 '/usr/bin/uglifycss' /tmp/inputdsbYCy`
as it's a node flag, not an uglifycss one

**Comment by stevenmusumeche** [comment]
Am I running the most recent commits? I ran this command:
```
$ npm install uglifycss
uglifycss@0.0.11 node_modules/uglifycss
```
I got the same error as before, even with the modified command you listed.  Here is the CSS file that is causing the error: https://gist.github.com/stevenmusumeche/da66a87648d9c5c958c5

**Comment by fmarcia** [comment]
You can run npm to update uglifycss now.
I tried to run it against your file and it worked fine.

**Comment by stevenmusumeche** [comment]
@fmarcia thanks again for your help, but I am still having the same issue even after updating to uglifycss@0.0.12.  I am running node v0.12.0, is that what you are running?

I've tried two things:

```
uglifycss /tmp/inputmpkpCa
```
I immediately get `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`

Next I tried

```
'/usr/local/bin/node' --max_old_space_size=2000000 '/usr/bin/uglifycss' /tmp/inputmpkpCa
```

and immediate got:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)
```

Any other ideas of how I can figure out what's happening?  Is this a node issue or something to do with the configuration of my VM?

**Comment by stevenmusumeche** [comment]
I ran node in debug mode and this is the output that I got, seems like the issue is happening on line 29?

```
$ node debug /usr/bin/uglifycss /tmp/inputmpkpCa
< Debugger listening on port 5858
connecting to port 5858... ok
break in /usr/lib/node_modules/uglifycss/uglifycss:29
 27  */
 28
>29 var util = require('util'),
 30     uglifycss = require('./'),
 31     uglies = [],
```

**Comment by stevenmusumeche** [comment]
Based on the above error I removed node from my system and reinstalled using yum and the problem disappeared.  Thank you so much for your help!

**Comment by ikodev** [comment]
I got the same problem (out of memory) however I fix it with a simple reinstallation of uglifyjs and uglifycss in my node_modules/ local project directory (symfony). Seems like it was a version problem ? I don't know... but it's works now !
