### ISSUE TITLE
uglifycss uses CRLF 

### ISSUE THREAD

**Issue by Keruspe** [fmarcia/UglifyCSS#28]
Hi,

Currently, uglifycss uses CRLF for lines ending ("\r\n"), hich does not seem to match the standards used by (every?) other node module.

This has an annoying drawback of failing to launch on some unix systemd because it tries to launch `node\r` instead of `node` if you call `uglifycss` directly and node `node uglifycss`

**Comment by guillem-cuberes** [comment]
It's failing in Ubuntu Server.

This fixed it: 
```sudo sed -i 's/\r//g' /usr/local/lib/node_modules/uglifycss/uglifycss```
