### ISSUE TITLE
UglifyCSS looses parts of the css when there's a comment ending with '.../*/' 

### ISSUE THREAD

**Issue by azine** [fmarcia/UglifyCSS#33]
Hi,

I had a strange issue, where uglifycss lost some parts of my css while uglifying. Through trial and error I was able to pin it down a bit.

In some of my CSS I have comments that are "marked" like this:

>`/*//////////////////////////////////////////////*/`
>`/* Some interesting bla bla bla */`

With the latest version of uglifycss (0.0.15) some parts of the css will be lost. It worked with an older version, I only update a few weeks ago.

I found out, that a slash following and asterik and another slash at the end of a comment => `.../*/` or `/*///   ///*/` causes the problems.

I think uglify should handle this better or throw an error indicating that it appears to be a nested comment. See also http://www.w3.org/TR/CSS21/syndata.html#comments

Cheers,
Dominik

**Comment by fmarcia** [comment]
UglifyCSS is not a parser so it hardly detects this kind of construct. I'm going to add a warning at the beginning of README.md about using only valid CSS as input.
Maybe you could use a tool like [csslint.net] (https://github.com/CSSLint/csslint) in your build process.
Thanks for your report.

**Comment by azine** [comment]
Hi Franck,

thanx for your answer.

The point is having this ("/*/////*/") in the css IS valid according to the
w3c-link I posted in my issue report.

While this bug/issue persists in uglifycss, adding a comment to the readme
is surely a good idea.

Thanx for the tip with csslint. I'll take a look at it.

Cheers,
Dominik
Am 05.07.2015 15:32 schrieb "Franck Marcia" <notifications@github.com>:
