### ISSUE TITLE
please tag release here in Git

### ISSUE THREAD

**Issue by sunweaver** [fmarcia/UglifyCSS#34]
Dear maintainer of UglifyCSS,

I would love to bring uglifycss to Debian and the packaging process gets tremendously eased by upstream, if releases get (regularly) tagged on the upstream Git site.

Do you think, you could tag at least the last release (0.0.15) or even make a new release (with a tag)?

Thanks,
Mike Gabriel (aka sunweaver at debian.org)

**Comment by fmarcia** [comment]
It's done. I've tagged every version since the first one. Thanks for your interest.

**Comment by sunweaver** [comment]
> It's done. I've tagged every version since the first one. Thanks for
> your interest.

Thanks! Will maybe take a look the coming week, but surely after my vacation (back in last week of August).
