### ISSUE TITLE
Please add LICENSE file with exact wording of "MIT" license

### ISSUE THREAD

**Issue by sunweaver** [fmarcia/UglifyCSS#35]
Your README.md (and the headers of the source files) say(s), this source project is licensed under MIT license. Unfortunately, there are dozens of MIT licenses out there [1].

Please ship a copy of the meant MIT license, which very probably is the text well known under the MIT/Expat license [2].

This extra license file is a pre-requisite of getting your code into Debian. Once you have added that file, I'd suggest tagging a new version.

Thanks!
Mike

[1] https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT
[2] https://www.debian.org/legal/licenses/mit

**Comment by fmarcia** [comment]
A license file is now available in version 0.0.17.
Thank you!
Franck
