### ISSUE TITLE
Media Query / Null Byte hack for IE <9 gets modified

### ISSUE THREAD

**Issue by manuelbieh** [fmarcia/UglifyCSS#36]
Testcase:
```
@media \0screen\,screen\9 {
    .test {
        color: red;
    }
}
```

Is converted to:
`@media \0creen\,screen\9{.test{color:red}}`
-> there's an `s` missing after \0

I'm not sure if it is a wanted behavior or not but maybe you want to take a look at it ;)

**Comment by fmarcia** [comment]
Thanks for the report.
