### ISSUE TITLE
package.json engines : Node version

### ISSUE THREAD

**Issue by iGitScor** [fmarcia/UglifyCSS#39]
Hi,

Could you precise in your `package.json` file the node version number required for UglifyCSS if it's possible ?

```
"engines": {
    "node": ">=x.y.z"
  }
```

Thank you

**Comment by fmarcia** [comment]
Thanks for your report.
It looks to me uglifycss should work with any version of node.
What is the reason for this request? Have you encountered any problem?

**Comment by iGitScor** [comment]
Our team (@1001pharmacies) needs to install uglifyCSS in a new environment and we have to know if the installed version of node is compatible with this plugin.

**Comment by fmarcia** [comment]
`engines.node` missing in `package.json` is the same as using `engines.node = "*"` ([see there](https://docs.npmjs.com/files/package.json#engines)). As I never heard of any problem and from my own experience, I think it's the right value!

**Comment by iGitScor** [comment]
Can you tell me which version of node do you use for your development, even if I know there is no known problem with this plugin ? Thanks

**Comment by fmarcia** [comment]
I think I started this project with Node v0.3.* series in the beginning of 2011 and I'm using now the lastest version, v5.6.0.

**Comment by iGitScor** [comment]
Thank you very much
