### ISSUE TITLE
Please add an -o option to specify output file

### ISSUE THREAD

**Issue by martinlindhe** [fmarcia/UglifyCSS#45]
The issue is Windows...

When piping command output in a windows environment, you'll get UTF-16, so the on-disk size of the resulting minified file can actually grow larger than the un-minified input file that used the UTF-8 encoding.
If uglifycss knew how to write to disk by itself, we can avoid this headache.

**Comment by fmarcia** [comment]
Thanks for your feeback.
I'm about to push an update with an `--ouput` option. Could you test it before I publish it to NPM? Thanks.

**Comment by martinlindhe** [comment]
Confirmed working perfectly! Thank you very much for the quick response

**Comment by Berkmann18** [comment]
This isn't working on Linux with the latest version (v0.0.27).
