### ISSUE TITLE
UglifyCSS removes the % when assigned value is 0%

### ISSUE THREAD

**Issue by haripaddu** [fmarcia/UglifyCSS#46]
I am experiencing an issue where UglifyCSS removes "%" when I set the CSS value to be "0%".

For example, I have the following CSS code
`-webkit-flex: 1 1 0%; flex: 1 1 0%;`

and UglifyCSS minifies to
`-webkit-flex: 1 1 0; flex: 1 1 0;`

Due to this, the flex-basis doesn't get applied in IE 10 and the width of the content breaks. If I manually add "%", it seems to fix the issue in IE 10. As a matter of fact, it happens with other units too like "rem", "px", "em" etc.,

**Comment by fmarcia** [comment]
I'll check this. Thanks for your feedback.

**Comment by digamber89** [comment]
Hello is there any update on this ?
I have the same issue, I was able to do a temp fix by adding 0.00%

**Comment by haripaddu** [comment]
Is this fix out in 0.27 version? I just tried and it still happens

**Comment by fmarcia** [comment]
@haripaddu are you sure you used uglifycss 0.27?

With `test.css`:
```
a {
  -webkit-flex: 1 1 0%; flex: 1 1 0%;
}
```
`uglifycss test.css` outputs:
```
a{-webkit-flex:1 1 0%;flex:1 1 0%}
```

**Comment by haripaddu** [comment]
try this one
`-webkit-flex:1 0 0%; flex:1 0 0%;`
This particular combination didn't work. I didn't test the other combinations yet.

also, not that the following doesn't cause any errors in IE, but if you mention
`width:0%;`
it still outputs as `width:0;`

**Comment by fmarcia** [comment]
OK, I got it. It doesn't work when there are 2 zeros in a row. Thanks
