### ISSUE TITLE
npm install uglifycss -g not working

### ISSUE THREAD

**Issue by prithivraj** [fmarcia/UglifyCSS#48]
npm ERR! code E404
npm ERR! 404 no such package available : uglifycss
npm ERR! 404 
npm ERR! 404  'uglifycss' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by fmarcia** [comment]
Sorry but I can't reproduce this one
