### ISSUE TITLE
CSS3

### ISSUE THREAD

**Issue by kerkenit** [fmarcia/UglifyCSS#54]
I've got errors with _new_ CSS3 minify issues.
See examples in attachments (From the template I've bought)
Almost all files give errors. (I haven't tested them all)

[helpers.zip](https://github.com/fmarcia/UglifyCSS/files/1237077/helpers.zip)

assets/helpers/animate.css: line 1: .animated: command not found
assets/helpers/animate.css: line 2: -webkit-animation-duration:: command not found
assets/helpers/animate.css: line 3: animation-duration:: command not found
assets/helpers/animate.css: line 4: -webkit-animation-fill-mode:: command not found
assets/helpers/animate.css: line 5: animation-fill-mode:: command not found
assets/helpers/animate.css: line 6: syntax error near unexpected token `}'
assets/helpers/animate.css: line 6: `}'

**Comment by fmarcia** [comment]
It's not related to UglifyCSS. It doesn't raise this kind of errors
