### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by Berkmann18** [fmarcia/UglifyCSS#56]
# Problem
I'm trying to run this package as an NPM script (`"mincss": "uglifycss --ugly-comments"`) but whenever I do that it fails in finding the files I'm passing to it.
Oddly enough, using the absolute path (`../node_modules/uglifycss/uglifycss`) works.

# System
ArchLinux 4.13 x64
NPM version: 5.6.0
Node version: 9.4.0
uglifycss: 0.0.27 (latest version as I write this).

**Comment by fmarcia** [comment]
Did you try to install uglifycss globally, i.e. with `-p` parameter:
```
$ npm install -g uglifycss
```

**Comment by Berkmann18** [comment]
No, as I've only installed it locally.

**Comment by fmarcia** [comment]
If uglifycss is not in your path (i.e. in directories `echo $PATH | sed s/:/\\n/g` will list), npm will not find it and you'll have to use a complete path, like you did.

**Comment by Berkmann18** [comment]
Sounds like you need to implement a support for local usage then. I'll possibly use it globally but some might not and face the same issue.
