### ISSUE TITLE
Depend on supported node engine for ES6

### ISSUE THREAD

**Issue by schmunk42** [fmarcia/UglifyCSS#59]
I updated uglifycss to 0.0.28 on an engine which does not support ES6, would be good to add that dependency to `packages.json`.

See https://docs.npmjs.com/files/package.json#engines

**Comment by fmarcia** [comment]
Thanks for catching this

**Comment by mijiang168** [comment]
> I updated uglifycss to 0.0.28 on an engine which does not support ES6, would be good to add that dependency to `packages.json`.
> 
> 
> 
> See https://docs.npmjs.com/files/package.json#engines
