### ISSUE TITLE
[Feature]Add option to export to file

### ISSUE THREAD

**Issue by KenBonny** [fmarcia/UglifyCSS#66]
I use JetBrains Rider to develop and I want to add a file watcher to my css files. I'd love to use your very nice npm package to do this, but I need an option to export to a file. I can't use the command line ``` > style.min.css``` option.

Could you add an option such as ```-destination style.min.css```.

**Comment by fmarcia** [comment]
Hi KenBonny,

There's an option for this: `--output <filename>`

**Comment by KenBonny** [comment]
I can't believe I missed that. I rectified my incorrect blog post and posted an update on twitter as well. Thanks!

https://kenbonny.net/2018/08/13/minifying-js-and-css-files-with-rider-file-watchers/
