### ISSUE TITLE
CSS Sourcemap

### ISSUE THREAD

**Issue by omidgfx** [fmarcia/UglifyCSS#67]
Hi, I have a less compiler that generates css and sourcemap, and I'm using uglifycss for compressing my css files, but the last line in each css file is` /*# sourceMappingURL=MYFILENAME.min.css.map */`
 so I need this comment to remain in output of uglifycss, Is there any particular option or way to do this ?

**Comment by fmarcia** [comment]
Thanks for using uglifycss.
You can add an exclamation point at the beginning of the comment. In this case, the comment will be preserved.
If it's not possible with `less`, you could insert a `sed` command in your build process using `# sourceMappingURL=`.
If you need the comment to be at the beginning of the line, add the option `--cute-comments` to the `uglifycss` command.
