### ISSUE TITLE
Removes HTML Space after ! Exclamation Mark

### ISSUE THREAD

**Issue by RyanPWalker** [fmarcia/UglifyCSS#70]
Using the `processString` method, it always strips out the space after an exclamation mark in HTML.  For example, "Good news!  You were accepted" is always outputted as "Good news!You were accepted" no matter how I compile it or what HTML entities I use.

**Comment by RyanPWalker** [comment]
Update:
This happens for any white space after a closing tag.
Also, I'm finding that it removes the % sign too in html?

**Comment by fmarcia** [comment]
Uglifycss is supposed to be used with css, not html
